features-v2.json
and remove unused nucliadb_node_sync_fs
=> add paragraph seek ff key

features-v2.json
Also, wait for resource to be indexed in stage
=> Turn on processed ingest message handling in prod

features-v2.json
Feature flags for generative models
=> Add feature flag for disabled generative models

features-v2.json
adds etna and atlas to disabled models in prod
=> add etna and atlas to disabled models in prod

features-v2.json
Add `application_allow-kb-management-from-nua-key` feature flag disabled for everyone.
=> [sc-8087] Update features-v2.json

features-v2.json
=> Revert "Disable read replica searches in stage"

features-v2.json
cleanup old application feature flag not in use anymore
=> Remove US from blocked zone on application side

features-v2.json
feature flagged until we test it properly and everything is in place
=> Add feature flag for new mistral model

features-v2.json
=> ⚠️⚠️⚠️ Global Stage Split - Disable regional KB and Nuakey edit/delete AND stop pushing stats

features-v2.json
=> Revert "turn on triton processing in stage"

features-v2.json
=> Revert "Revert "turn on triton processing in stage""

features-v2.json
=> Revert "Revert "Revert "turn on triton processing in stage"""

features-v2.json
Add FF for reranking based citations, currently only active for one of my kbs in stage
=> Add FF for reranking based citations

features-v2.json
enable rerank citations in stage
=> enable rerank citations in stage

features-v2.json
enable citations for my prod kb and disable mistral large
=> enable citations for my prod kb and disable mistral large

features-v2.json
Feature flag for enabling images found in links to be processed
=> Link images FF

.github/workflows/push-to-cdn.yaml
Add Github Action for pushing features-vs.json file to the CDN bucket
=> Add GHA to push features file to CDN

features-v2.json
This can be merged after promoting accounting to PROD
=> remove not used accounting flags

features-v2.json
disable claude 2 and gemini 1.0
=> disable claude 2 and gemini 1.0

features-v2.json
disable azure's chatgpt 4 on kb creation
=> disable azure's chatgpt 4

features-v2.json
=> HF emb under FF

features-v2.json
=> deactivate florence stage

features-v2.json
=> ff for florence local

features-v2.json
=> enable florence2 in prod

features-v2.json
enable multilingual citations for testing
=> enable multilingual citations for testing

features-v2.json
activate multilingual citations stage
=> activate multilingual citations stage

features-v2.json
enable multilingual citations for my kbs and cleaning up FF that are not useful
=> enable multilingual citations for my kbs and cleaning up FF

features-v2.json
=> Revert "Activate new KB v2 (vectorsets v0) in prod"

features-v2.json
=> Revert "Revert "Activate new KB v2 (vectorsets v0) in prod""

features-v2.json
=> add svp kb to FF

features-v2.json
Until we fix the facets performance problem
=> Disable pg catalog on prod

features-v2.json
enable multilingual citations in prod
TODO: remove this FF and cleanup learning code after it's up and running for a while
=> enable multilingual citations in prod

features-v2.json
=> nidx is back

features-v2.json
=> Revert "nidx for everyone"

features-v2.json
=> Revert "nidx up again"

features-v2.json
=> disable deepseek

features-v2.json
=> Enable Deepseek models

features-v2.json
Added:
Agents for: Eric, Claudia and OAppsNet
Labeller agent for: Eric, Claudia and OAppsNet
Ask agent for : Fedarb, SRS,Eric, Claudia and OAppsNet  
Graph agent for: Nuclia, SRS, Fedarb, Eric, Claudia and OAppsNet
=> Update features-v2.json. New Agent users

features-v2.json
disable all gemini2.0 but flash, since it's the only generally available in all zones
=> disable all gemini2.0 but flash

features-v2.json
=> Disable `aws-eu-south-2-1` zone

features-v2.json
Will wait until monday 24/02/2025 for a deploy to production
=> Remove unused nucliadb feature flags

features-v2.json
enable improved citations for everyone
=> enable improved citations for everyone

.github/scripts/validate_features.py, .github/workflows/ci.yaml, features-v2.json
Add a step to load the features file with mrflagly to assert that it has the proper format
=> Validate that features has the proper format

features-v2.json
=> Revert "disable reporting only in new global aws"

features-v2.json
=> Revert "test disable e2e zone stage"
